server:
  port: 8081
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserilazer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserilazer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serilazer: org.apache.kafka.common.serialization.StringDeserializer
      value-serilazer: org.apache.kafka.common.serialization.StringDeserializer